alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cat='bat'
alias cg='cd $(git rev-parse --show-toplevel)'
alias cp='cp -iv'
alias df='df -H'
alias egrep='egrep --color=auto'
alias eza='eza '
alias f='fd'
alias fd='fd '\''--no-ignore'\'''
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias h='history'
alias icat='kitty +kitten icat'
alias l='ls -lhAF'
alias la='ls -hA'
alias ll='ls -lh'
alias lla='eza -la'
alias ln='ln -iv'
alias ls='eza'
alias lt='eza --tree'
alias mdkir='mkdir'
alias mkdir='mkdir -pv'
alias mv='mv -iv'
alias n='nnn -e'
alias nnn='nnn_quitcd'
alias rm='rm -iv'
alias rs='rsync -avzP'
alias vim='nvim'
alias vimdiff='nvim -d'